### ISSUE TITLE
JPC_Core.js -> Loading shaders and other stuff not working out of NWJS (web export)

### ISSUE THREAD

**Issue by scswinter** [Jim00000/RMMZ-Plugin-Collection#1]
Loading shaders and other stuff not working out of NWJS (web export). Require, fs, and other stuff are only available if Utils.isNwjs() is true. Otherwise, it should be done with html5 apis like fetch or similar.

**Comment by Jim00000** [comment]
21bba54 & 6753898 might fix that issue.

**Comment by scswinter** [comment]
It works, thanks.
