### ISSUE TITLE
Add the r, g, b, alpha and a (x, y) speed to the JPC_Cloud.js

### ISSUE THREAD

**Issue by scswinter** [Jim00000/RMMZ-Plugin-Collection#5]
It's possible? Thanks!

**Comment by Jim00000** [comment]
1f9adea adds the features to config color, density and speed of fog. 
As for alpha channel, it is not used right now but you can adjust density parameter to control the transparency of fog.
JPC_Cloud.js is renamed to JPC_Fog.js.
The original cloud effect can be reproduced with parameters:
- fogcolor : [R: 0.0, G: 0.0, B: 0.0] 
- density   : 0.6
